// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOj8ttwofs-iPWMsqyyo5N45BUJPj1Qi8',
    appId: '1:841542336430:web:2c93fa71b5397c34ecd23f',
    messagingSenderId: '841542336430',
    projectId: 'share-space-3a0e5',
    authDomain: 'share-space-3a0e5.firebaseapp.com',
    storageBucket: 'share-space-3a0e5.appspot.com',
    measurementId: 'G-0L6BRXMVYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwR8vTyEVKNN-zkZghsQnbE7x4i73As5A',
    appId: '1:841542336430:android:66d16a9d8cc363adecd23f',
    messagingSenderId: '841542336430',
    projectId: 'share-space-3a0e5',
    storageBucket: 'share-space-3a0e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwN2L8LGGJVFO-1WG9X2KkDnmMVCKyIPc',
    appId: '1:841542336430:ios:9cb009bd8bd29344ecd23f',
    messagingSenderId: '841542336430',
    projectId: 'share-space-3a0e5',
    storageBucket: 'share-space-3a0e5.appspot.com',
    androidClientId: '841542336430-m7frpire00bvl7qu008284u745gad6ei.apps.googleusercontent.com',
    iosClientId: '841542336430-bop85c618u3nmj2v6rkf5gmu3l9cjogl.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareSpace',
  );
}
